"""
Backup System (PR #83)
Creates a tarball of critical state files and uploads to
GitHub Releases as a versioned daily backup.

WHY THIS EXISTS:
  Without this, an accidental rm -rf, git history corruption,
  or repository deletion = MONTHS of irreplaceable data lost.

WHAT GETS BACKED UP:
  Everything in data/ folder (most critical)
  + key config files for full recovery

STRATEGY:
  - Daily backup at 23:00 UTC (after market + reports done)
  - Named: backup-YYYY-MM-DD.tar.gz
  - Stored as GitHub Release asset (free, versioned, durable)
  - Last 30 days kept; older auto-pruned

RECOVERY:
  gh release download backup-2026-05-02
  tar xzf backup-2026-05-02.tar.gz
"""
import subprocess
import sys
import tarfile
import json
from pathlib import Path
from datetime import datetime, timezone, timedelta

BACKUP_PATHS = [
    "data",
    "config.yaml",
    "watchlist.json",
]
RETAIN_DAYS = 30
BACKUP_DIR = Path("/tmp/backups")


def get_today_tag() -> str:
    return f"backup-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"


def create_tarball() -> Path:
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    tag = get_today_tag()
    tarball = BACKUP_DIR / f"{tag}.tar.gz"

    print(f"[backup] Creating tarball: {tarball}")

    file_count = 0
    total_bytes = 0

    with tarfile.open(tarball, "w:gz") as tar:
        for path_str in BACKUP_PATHS:
            path = Path(path_str)
            if not path.exists():
                print(f"[backup]   skip (not found): {path_str}")
                continue
            print(f"[backup]   + adding: {path_str}")
            tar.add(path, arcname=path_str)

            if path.is_file():
                file_count += 1
                total_bytes += path.stat().st_size
            else:
                for f in path.rglob("*"):
                    if f.is_file():
                        file_count += 1
                        total_bytes += f.stat().st_size

    size_mb = tarball.stat().st_size / 1024 / 1024
    print(f"[backup] OK Tarball ready: {size_mb:.2f} MB "
          f"({file_count} files, {total_bytes/1024/1024:.2f} MB raw)")
    return tarball


def create_release(tarball: Path) -> bool:
    tag = get_today_tag()
    title = f"Daily Backup {tag.replace('backup-', '')}"

    notes = (
        f"# Automated Daily Backup\n\n"
        f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
        f"**Size:** {tarball.stat().st_size / 1024 / 1024:.2f} MB\n\n"
        f"## Contents\n"
        f"- data/ (news signals, logs, watchlist, portfolio state)\n"
        f"- config.yaml\n\n"
        f"## Recovery\n"
        f"```\n"
        f"gh release download {tag}\n"
        f"tar xzf {tarball.name}\n"
        f"```\n\n"
        f"Auto-generated by PR #83 backup system.\n"
    )
    notes_file = BACKUP_DIR / "release_notes.md"
    notes_file.write_text(notes)

    print(f"[backup] Cleaning any existing release for {tag}...")
    subprocess.run(
        ["gh", "release", "delete", tag, "--yes", "--cleanup-tag"],
        capture_output=True
    )

    print(f"[backup] Creating release: {tag}")
    result = subprocess.run(
        ["gh", "release", "create", tag,
         str(tarball),
         "--title", title,
         "--notes-file", str(notes_file)],
        capture_output=True, text=True
    )

    if result.returncode != 0:
        print(f"[backup] FAIL Release creation failed:")
        print(f"  stdout: {result.stdout}")
        print(f"  stderr: {result.stderr}")
        return False

    print(f"[backup] OK Release created: {result.stdout.strip()}")
    return True


def prune_old_backups():
    print(f"[backup] Pruning backups older than {RETAIN_DAYS} days...")

    result = subprocess.run(
        ["gh", "release", "list", "--limit", "100", "--json",
         "tagName,createdAt"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"[backup]   warn: Could not list releases: {result.stderr}")
        return

    releases = json.loads(result.stdout)
    cutoff = datetime.now(timezone.utc) - timedelta(days=RETAIN_DAYS)
    deleted = 0

    for rel in releases:
        tag = rel["tagName"]
        if not tag.startswith("backup-"):
            continue
        created = datetime.fromisoformat(rel["createdAt"].replace("Z", "+00:00"))
        if created < cutoff:
            print(f"[backup]   delete old: {tag} (from {created.date()})")
            subprocess.run(
                ["gh", "release", "delete", tag, "--yes", "--cleanup-tag"],
                capture_output=True
            )
            deleted += 1

    if deleted == 0:
        print(f"[backup]   OK No old backups to prune")
    else:
        print(f"[backup]   OK Pruned {deleted} old backup(s)")


def main():
    print("=" * 63)
    print(f"DAILY BACKUP - {datetime.now(timezone.utc).isoformat()}")
    print("=" * 63)

    try:
        tarball = create_tarball()
        success = create_release(tarball)
        if not success:
            sys.exit(1)
        prune_old_backups()
        print("=" * 63)
        print("OK BACKUP COMPLETE")
        print("=" * 63)
    except Exception as e:
        print(f"FAIL BACKUP FAILED: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()