"""Reads today's picks from data/picks_log.csv and prints clean Markdown for the GitHub issue email."""
import csv
from datetime import datetime
from pathlib import Path

today = datetime.now().strftime("%Y-%m-%d")
rows = []
p = Path("data/picks_log.csv")
if p.exists():
    with p.open() as f:
        for r in csv.DictReader(f):
            if r.get("pick_date") == today:
                rows.append(r)

print(f"# 📈 Daily Stock Picks — {today}\n")

if not rows:
    print("_No picks were generated today (filters too strict, or earnings season blocking candidates)._")
    raise SystemExit

print(f"**{len(rows)} picks** generated. Regime: `{rows[0].get('regime','?')}`  •  SPY close: `${rows[0].get('spy_close','?')}`  •  CAPE: `{rows[0].get('cape','?')}`\n")
print("> ⚠️ Educational only. Not financial advice. Always verify before trading.\n")

print("## 🎯 Picks\n")
print("| # | Ticker | Company | Score | Entry | Stop Loss | Take Profit | R:R | Qty | Earnings |")
print("|---|--------|---------|-------|-------|-----------|-------------|-----|-----|----------|")

for i, r in enumerate(rows, 1):
    try:
        entry = float(r["entry"]); sl = float(r["stop_loss"]); tp = float(r["take_profit"])
        risk_pct = (entry - sl) / entry * 100
        reward_pct = (tp - entry) / entry * 100
    except Exception:
        entry = r.get("entry","?"); sl = r.get("stop_loss","?"); tp = r.get("take_profit","?")
        risk_pct = reward_pct = 0
    d2e = r.get("days_to_earnings","")
    earn = f"{d2e}d" if d2e else "—"
    print(f"| {i} | **{r['ticker']}** | {r.get('company','')[:30]} | {float(r['score']):.2f} | "
          f"${entry:.2f} | ${sl:.2f} (−{risk_pct:.1f}%) | ${tp:.2f} (+{reward_pct:.1f}%) | "
          f"{r.get('risk_reward','2.0')} | {r.get('qty','-')} | {earn} |")

print("\n## 📋 Trade Plan Notes\n")
print("- **Entry**: Suggested limit price (use limit orders, not market)")
print("- **Stop Loss**: Hard exit if breached — protects capital")
print("- **Take Profit**: Target exit (R:R 2.0 means 2× reward vs risk)")
print("- **Earnings**: Days until next earnings report (skipped if <5d)")
print(f"\n---\n_Generated by [daily-stock-agent](https://github.com/anjanneogi13/daily-stock-agent) at {datetime.now().strftime('%H:%M UTC')}_")
