"""T46 / Pillar 6: Yearly Report (markdown scaffold).

Generates a year-end summary similar to Buffett's annual letter.
PDF/LLM/tax-form generation explicitly deferred (multi-week build).

Usage:
    python -m src.yearly_report [--year 2026]
"""
from __future__ import annotations
import argparse
import csv
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

PICKS = Path("data/picks_log.csv")
REPORTS = Path("reports/yearly")


def _to_float(v) -> Optional[float]:
    try: return float(v)
    except (TypeError, ValueError): return None


def _load_year(year: int) -> List[Dict]:
    if not PICKS.exists():
        return []
    out = []
    with PICKS.open() as f:
        for row in csv.DictReader(f):
            d = (row.get("pick_date") or "")[:4]
            if d == str(year):
                out.append(row)
    return out


def build_report(year: Optional[int] = None) -> Dict:
    year = year or datetime.now().year
    picks = _load_year(year)
    closed = [p for p in picks if (p.get("evaluation_status") or "").lower()
              in ("sl_hit","tp_hit","max_hold","sl_gap","tp_gap")]
    rs = [r for r in (_to_float(p.get("r_multiple")) for p in closed) if r is not None]
    alphas = [a for a in (_to_float(p.get("alpha_pct")) for p in closed) if a is not None]
    wins = sum(1 for r in rs if r > 0)
    return {
        "year":     year,
        "picks":    len(picks),
        "closed":   len(closed),
        "wins":     wins,
        "win_rate": round(wins / max(len(rs),1), 3) if rs else 0.0,
        "total_r":  round(sum(rs), 3) if rs else 0.0,
        "mean_r":   round(sum(rs)/len(rs), 3) if rs else 0.0,
        "alpha":    round(sum(alphas)/len(alphas), 3) if alphas else 0.0,
    }


def format_markdown(r: Dict) -> str:
    return "\n".join([
        f"# 📚 Annual Report — {r['year']}",
        "",
        "## Headline metrics",
        f"- Total picks: **{r['picks']}**",
        f"- Closed: **{r['closed']}**",
        f"- Win rate: **{r['win_rate']:.0%}** ({r['wins']}/{r['closed']})",
        f"- Total R: **{r['total_r']:+.2f}**",
        f"- Mean R/trade: **{r['mean_r']:+.2f}**",
        f"- Avg alpha vs SPY: **{r['alpha']:+.2f}%**",
        "",
        "## Notes",
        "- Tax-loss harvesting · wash-sale ledger · 1099-equiv · Buffett-style narrative",
        "  are scheduled for v2 (PDF + LLM pipeline — multi-week build).",
        "",
        f"_Auto-generated by `src/yearly_report.py` on "
        f"{datetime.now().date().isoformat()}._",
    ])


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--year", type=int, default=datetime.now().year)
    ap.add_argument("--out",  type=str, default=None)
    args = ap.parse_args(argv)
    r = build_report(args.year)
    md = format_markdown(r)
    REPORTS.mkdir(parents=True, exist_ok=True)
    out = Path(args.out) if args.out else REPORTS / f"yearly_{r['year']}.md"
    out.write_text(md + "\n")
    print(f"✅ wrote {out}  (n={r['closed']} closed, R={r['total_r']:+.2f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
